name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "958f3364acf84616af0eece7ba620a29"

[observability]
enabled = true
head_sampling_rate = 1
